// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetInterviews.Infrastructure.Data;

#nullable disable

namespace NetInterviews.Infrastructure.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20250206135940_MovieData")]
    partial class MovieData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("NetInterviews.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Comedy"
                        });
                });

            modelBuilder.Entity("NetInterviews.Core.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Seen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Rating = 4,
                            Seen = false,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 5,
                            Rating = 2,
                            Seen = false,
                            Title = "Mr Bean"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Rating = 4,
                            Seen = false,
                            Title = "Collateral"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Rating = 4,
                            Seen = false,
                            Title = "The Haunting"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Rating = 4,
                            Seen = false,
                            Title = "Don't move"
                        });
                });

            modelBuilder.Entity("NetInterviews.Core.Models.Movie", b =>
                {
                    b.HasOne("NetInterviews.Core.Models.Category", "Category")
                        .WithMany("Movies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NetInterviews.Core.Models.Category", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
